services:
  payments-db:
    image: postgres:16
    container_name: payments-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5432:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data

volumes:
  payments_db_data:
