spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments
    password: payments

  jpa:
    hibernate:
      ddl-auto: update
